In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math as math

In [2]:
main_dir = os.getcwd().split('\\')[-1]
if main_dir != 'boston-marathons' and main_dir != 'boston-marathons-Copy1':
    os.chdir("../..")
    main_dir = os.getcwd().split('\\')[-1]
print(main_dir)

boston-marathons-Copy1

In [3]:
df = pd.read_csv('data/clean/boston_clean.csv')
df.head()

,Name,M/F,Age,Country,City,Pace,5K,10K,15K,20K,25K,30K,35K,40K,Official Time,Year
0,"Desisa, Lelisa",M,25,ETH,Ambo,3.065431,0.245278,0.495278,0.749167,1.008056,1.268611,1.533333,1.799722,2.044167,2.154722,2015
1,"Tsegay, Yemane Adhane",M,30,ETH,Addis Ababa,3.086144,0.245278,0.495278,0.749444,1.007778,1.268611,1.533056,1.799722,2.045000,2.163333,2015
2,"Chebet, Wilson",M,29,KEN,Marakwet,3.096500,0.245278,0.495278,0.749167,1.008056,1.268611,1.533333,1.799722,2.050278,2.172778,2015
3,"Kipyego, Bernard",M,28,KEN,Eldoret,3.106856,0.245278,0.495556,0.750278,1.008056,1.268611,1.533333,1.800833,2.063056,2.179722,2015
4,"Korir, Wesley",M,32,KEN,Kitale,3.106856,0.245278,0.495556,0.749444,1.007778,1.268611,1.533333,1.799722,2.057500,2.180278,2015

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79638 entries, 0 to 79637
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           79638 non-null  object
 1   M/F            79638 non-null  object
 2   Age            79638 non-null  int64
 3   Country        79638 non-null  object
 4   City           79637 non-null  object
 5   Pace           79638 non-null  float64
 6   5K             79409 non-null  float64
 7   10K            79524 non-null  float64
 8   15K            79587 non-null  float64
 9   20K            79553 non-null  float64
 10  25K            79557 non-null  float64
 11  30K            79550 non-null  float64
 12  35K            79552 non-null  float64
 13  40K            79562 non-null  float64
 14  Official Time  79638 non-null  float64
 15  Year           79638 non-null  int64
dtypes: float64(10), int64(2), object(4)
memory usage: 9.7+ MB

#### FEATURES

In [6]:
# PLACES

# Place_Year column
df = df.sort_values(by=["Year", "Official Time"])
df["Place_Year"] = df.groupby("Year").cumcount() + 1

# Place_Global column
df = df.sort_values(by='Official Time').reset_index(drop=True)
df["Place_Global"] = range(1, len(df)+1)

In [7]:
# AGE GROUPS
age = df['Age']

bins = list(np.arange(age.min(), 70, 4)) + [age.max() + 1]
labels = [f"{b}–{bins[i+1]-1}" for i, b in enumerate(bins[:-2])] + ["70+"]

df["Age Group"] = pd.cut(age, bins=bins, labels=labels, right=False)

In [8]:
# CONTINENTS
continent_map = pd.read_csv("data/mappings/country_to_continent.csv")
df = df.merge(continent_map, on="Country", how="left")
df["Continent"] = df["Continent"].fillna("Unknown")

In [9]:
df.columns

Index(['Name', 'M/F', 'Age', 'Country', 'City', 'Pace', '5K', '10K', '15K',
       '20K', '25K', '30K', '35K', '40K', 'Official Time', 'Year',
       'Place_Year', 'Place_Global', 'Age Group', 'Continent'],
      dtype='object')

In [10]:
# columns order
df = df[['Name', 'M/F', 'Age', 'Age Group', 'Country', 'Continent', 'City', 'Pace', '5K', '10K', '15K', '20K', '25K', '30K', '35K', '40K', 'Official Time', 'Year', 'Place_Year', 'Place_Global']]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79638 entries, 0 to 79637
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           79638 non-null  object
 1   M/F            79638 non-null  object
 2   Age            79638 non-null  int64
 3   Age Group      79638 non-null  category
 4   Country        79638 non-null  object
 5   Continent      79638 non-null  object
 6   City           79637 non-null  object
 7   Pace           79638 non-null  float64
 8   5K             79409 non-null  float64
 9   10K            79524 non-null  float64
 10  15K            79587 non-null  float64
 11  20K            79553 non-null  float64
 12  25K            79557 non-null  float64
 13  30K            79550 non-null  float64
 14  35K            79552 non-null  float64
 15  40K            79562 non-null  float64
 16  Official Time  79638 non-null  float64
 17  Year           79638 non-null  int64
 18  Place_Year     79638 non-null  int64
 19  Place_Global   79638 non-null  int64
dtypes: category(1), float64(10), int64(4), object(5)
memory usage: 11.6+ MB

In [12]:
df.tail(15)

,Name,M/F,Age,Age Group,Country,Continent,City,Pace,5K,10K,15K,20K,25K,30K,35K,40K,Official Time,Year,Place_Year,Place_Global
79623,"Avelino, Andrew R.",M,25,22–25,USA,North America,Fayetteville,10.356187,0.534167,1.092500,1.871389,2.828056,3.838611,4.833611,5.896667,6.905833,7.283056,2017,26407,79624
79624,"Hantel, Johanna",F,57,54–57,USA,North America,Malvern,10.428680,0.886389,1.726667,2.543333,NaN,4.255833,5.110278,6.009167,6.910556,7.326944,2017,26408,79625
79625,"Reilly, Bill",M,64,62–65,USA,North America,New York,10.449392,0.676111,1.455278,2.288056,3.194444,4.102778,5.119167,6.101944,6.935556,7.345556,2017,26409,79626
79626,"Hall, Steven J",M,43,42–45,USA,North America,Yardley,10.490817,0.349444,0.694722,1.041389,1.392778,1.750000,2.122500,2.522500,6.905556,7.373056,2016,26625,79627
79627,"Prescott, Francine J.",F,64,62–65,USA,North America,Boynton Beach,10.884352,0.837500,1.725278,2.614722,3.540556,4.431389,5.328889,6.288611,7.226111,7.648889,2015,26594,79628
79628,"Weidenkeller, Tina M.",F,46,46–49,USA,North America,Rossmoor,11.091476,0.784167,1.533611,2.480278,3.474167,4.458889,5.403333,6.488889,NaN,7.798889,2016,26626,79629
79629,"Marseilles, Jami E.",F,47,46–49,USA,North America,Huntington Beach,11.091476,0.784444,1.533889,2.480556,3.474444,4.459167,5.403333,6.489167,7.420833,7.798889,2016,26627,79630
79630,"Emerson, Annette C.",F,61,58–61,USA,North America,Old Town,11.174325,0.810000,1.660833,2.653611,3.599444,4.545556,5.532778,6.482222,7.438611,7.858333,2015,26595,79631
79631,"Rigsby, Scott",M,48,46–49,USA,North America,Alpharetta,11.340024,0.660000,1.286667,2.002778,2.981944,4.453889,5.620278,6.651944,7.689722,7.970556,2017,26410,79632
79632,"Cerveny, Nona",F,66,70+,USA,North America,Scottsdale,11.371093,0.884167,1.787778,2.695833,3.618611,4.564167,5.648889,6.647500,7.605000,7.992500,2015,26596,79633
79633,"Buccilli, Alfred P.",M,53,50–53,USA,North America,Lynnfield,11.391805,0.817778,1.670000,2.558611,3.528056,4.488889,5.519722,6.559722,7.593889,8.010278,2015,26597,79634
79634,"Reilly, William",M,62,62–65,USA,North America,Kew Garden,11.526436,0.670556,1.471667,2.446111,3.478056,4.601667,5.728889,6.858611,7.691111,8.100278,2015,26598,79635
79635,"Ganem, William J.",M,39,38–41,USA,North America,Reedsburg,11.940683,0.706111,1.496944,2.396944,3.415000,4.431389,5.490833,6.701111,7.905833,8.390833,2016,26628,79636
79636,"Farler, Daryl R.",M,35,34–37,USA,North America,Franklin,11.982108,0.599444,1.252500,1.969167,2.820833,4.120833,5.466389,6.830833,7.986667,8.419167,2016,26629,79637
79637,"Haslet, Adrianne K.",F,35,34–37,USA,North America,Boston,15.223594,0.747778,1.591944,2.682778,4.494444,NaN,7.610556,NaN,NaN,10.506389,2016,26630,79638

In [13]:
df.to_csv('data/clean/boston_features.csv', index=False)